# https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28#event-object-common-properties

name: Build and Push Quarkus Docker Image

on:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the application name
        shell: bash
        run: echo "app_name=`echo $GITHUB_REPOSITORY | awk -F/ '{print $NF}'`" >> $GITHUB_ENV

      - name: Build Quarkus Docker Image
        run: mvn install -Dquarkus.container-image.build=true -Dquarkus.container-image.group="${{ secrets.DOCKER_USERNAME }}" -Dquarkus.container-image.name=${{ env.app_name }} -Dquarkus.container-image.tag=${{ github.event.pull_request.head.sha }}


      - name: Check Docker images
        run: docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.app_name }}:${{ github.event.pull_request.head.sha }}

#      - name: Archive Kubernetes manifests
#        uses: actions/upload-artifact@v2
#        with:
#          name: kubernetes.yml
#          path: target/kubernetes/kubernetes.yml
